#!/bin/bash

if [[ ! -f "mips_assembler" ]]; then
  echo "executable not found" >&2
  exit 1
fi

DEFAULT_OUT="a.bin"
if [[ $# == 1 ]]; then
  if [[ $1 == "-h" ]]; then
    cat README.md
    exit 0
  else
    ./mips_assembler "$1" $DEFAULT_OUT
  fi
elif [[ $# == 2 ]]; then
  if [[ $1 == "-h" ]]; then
    cat README.md
    exit 0
  fi
  ./mips_assembler "$1" "$2"
  exit $?
else
  echo "invalid arguments. run ./build -h or consult README.md" >&2
  exit 1
fi
